name: "❓ Question"
description: "Ask a question about the project or its features"
title: "[Question]: "
labels: [ "Question" ]
body:
- type: markdown
  attributes:
    value: "Please search [here](https://github.com/p0loskun/nykon.me/issues/labels/question) to ensure your question hasn’t already been answered."
    
- type: textarea
  attributes:
    label: "Question description"
    description: |
      Clearly state your question, providing as much detail as possible to make it easy to understand.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: "Additional context"
    description: |
      Provide additional context, background information, or examples that help clarify your question.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false

- type: checkboxes
  attributes:
    label: "Acknowledgements"
    description: "Your question may be closed if these steps are not followed."
    options: 
      - label: "I have checked existing issues to ensure my question has not already been answered."
        required: true
      - label: "I have written a clear and concise question in the appropriate section."
        required: true
      - label: "I have filled out all of the requested information in this issue properly."
        required: true
